sudo: false
dist: trusty
git:
  submodules: false # doesn't need 'em for tests
language: perl
perl:
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26.0"
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE yourdatabase ENCODING=utf8;" -U postgres
  - sqitch deploy --target travis
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
env:
  - MOJO_MODE=travis
script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" prove -r t
after_success:
  - cover -report codecov
