sudo: false
dist: trusty
language: perl
perl:
  - "5.20"
  - "5.22"
  - "5.24"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE yourdatabase ENCODING=utf8;" -U postgres
  - sqitch deploy --target travis
env:
  - MOJO_MODE=travis
script: prove -r t
