sudo: false
language: perl
perl:
  - "5.20"
  - "5.22"
  - "5.24"
services:
  - postgresql
addons:
  postgresql: "9.6"
dist: trusty
before_script:
  - psql -c "CREATE DATABASE yourdatabase ENCODING=utf8;" -U postgres
  - cp config/travis.yml config/local.yml
script: prove -r t
