---
defaults:
  loaded: true
app:
  host: localhost
  port: 7777
  workers: 1
  backlog: 128
  session:
    expires: 2419200 # 4 weeks
database:
  host: localhost
  name: yourdatabase
  user: yourself
  password: secured
  dbi_attributes:
    quote_char: '"'
    name_sep: '.'
    pg_enable_utf8: 1
redis:
  default:
    host: localhost
    port: 6379
    index: 1
  session:
    host: localhost
    port: 6379
    index: 2
