#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename qw( dirname );
use File::Spec ();
use Cwd qw( abs_path );

my $SCRIPT_PATH;

BEGIN {
    $SCRIPT_PATH = $0;
    while ( -l $SCRIPT_PATH ) {
        my $dir = dirname( $SCRIPT_PATH );
        $SCRIPT_PATH = readlink $SCRIPT_PATH;
        $SCRIPT_PATH = File::Spec->rel2abs( $SCRIPT_PATH, $dir );
    }
    chdir( dirname( $SCRIPT_PATH ). '/..' );
}

use lib qw( lib );

use YourCompany::Perl::UTF8;

use open ':std', ':encoding(UTF-8)';

use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('YourCompany::App');
