#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename qw( dirname );
use File::Spec ();
use Cwd qw( abs_path );
use open ':std', ':encoding(UTF-8)';

my $SCRIPT_PATH;

BEGIN {
    $SCRIPT_PATH = $0;
    while ( -l $SCRIPT_PATH ) {
        my $dir = dirname( $SCRIPT_PATH );
        $SCRIPT_PATH = readlink $SCRIPT_PATH;
        $SCRIPT_PATH = File::Spec->rel2abs( $SCRIPT_PATH, $dir );
    }
    chdir( dirname( $SCRIPT_PATH ). '/..' );
}

use lib qw( lib );

use YourCompany::Config;

my $BASE_FOLDER = abs_path( dirname( $SCRIPT_PATH ). '/..' );

$ENV{MOJO_REVERSE_PROXY} = 1;

exec(
    "/usr/bin/env",
    "starman",
    "-E", YourCompany::Config->app->{mode},
    "--preload-app",
    "-Ilib",
    "--listen", YourCompany::Config->app->{host}. ":". YourCompany::Config->app->{port},
    "--workers", YourCompany::Config->app->{workers},
    "--backlog", YourCompany::Config->app->{backlog},
    "--disable-proctitle",
    "script/http.pl",
);
