#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename qw( dirname );
use File::Spec ();
use Cwd qw( abs_path );
use open ':std', ':encoding(UTF-8)';

use constant {
    DEFAULT_HOST        => 'localhost',
    DEFAULT_PORT        => 7777,
    DEFAULT_WORKERS     => 1,
    DEFAULT_BACKLOG     => 128,
    DEFAULT_ENVIRONMENT => 'development',
};

my $SCRIPT_PATH;

BEGIN {
    $SCRIPT_PATH = $0;
    while ( -l $SCRIPT_PATH ) {
        my $dir = dirname( $SCRIPT_PATH );
        $SCRIPT_PATH = readlink $SCRIPT_PATH;
        $SCRIPT_PATH = File::Spec->rel2abs( $SCRIPT_PATH, $dir );
    }
    chdir( dirname( $SCRIPT_PATH ). '/..' );
}

use lib qw( lib );

my $BASE_FOLDER = abs_path( dirname( $SCRIPT_PATH ). '/..' );

$ENV{MOJO_REVERSE_PROXY} = 1;

my $appcfg = {};

exec(
    "/usr/bin/env",
    "starman",
    "-E", ( $appcfg->{environment} || DEFAULT_ENVIRONMENT ),
    "--preload-app",
    "-Ilib",
    "--listen", ( $appcfg->{host} || DEFAULT_HOST ). ":". ( $appcfg->{port} || DEFAULT_PORT ),
    "--workers", ( $appcfg->{workers} || DEFAULT_WORKERS ),
    "--backlog", ( $appcfg->{backlog} || DEFAULT_BACKLOG ),
    "--disable-proctitle",
    "script/http.pl",
);
