#!/usr/bin/env perl

use strict;
use warnings;
use feature 'say';

use File::Basename qw( dirname );
use File::Spec ();

my $SCRIPT_PATH = $0;
while ( -l $SCRIPT_PATH ) {
    my $dir = dirname( $SCRIPT_PATH );
    $SCRIPT_PATH = readlink $SCRIPT_PATH;
    $SCRIPT_PATH = File::Spec->rel2abs( $SCRIPT_PATH, $dir );
}

my $BASE_FOLDER = dirname( $SCRIPT_PATH ). '/..';

# $ENV{PGHOST}     = $dbcfg->{host} // 'localhost';
# $ENV{PGPORT}     = $dbcfg->{port} // 5432;
# $ENV{PGUSER}     = $dbcfg->{user};
# $ENV{PGPASSWORD} = $dbcfg->{password};
# $ENV{PGDATABASE} = $dbcfg->{database};

exec(
    '/usr/bin/env',
    'pgcli',
    @ARGV,
);
