#!/usr/bin/env perl

use strict;
use warnings;
use feature 'say';

use File::Basename qw( dirname );
use File::Spec ();
use Cwd qw( abs_path );

use lib::abs qw( ../lib );

use YourCompany::Config;

my $SCRIPT_PATH = $0;
while ( -l $SCRIPT_PATH ) {
    my $dir = dirname( $SCRIPT_PATH );
    $SCRIPT_PATH = readlink $SCRIPT_PATH;
    $SCRIPT_PATH = File::Spec->rel2abs( $SCRIPT_PATH, $dir );
}

my $dbcfg = YourCompany::Config->database;

$ENV{PGHOST}     = $dbcfg->{host} // 'localhost';
$ENV{PGPORT}     = $dbcfg->{port} // 5432;
$ENV{PGUSER}     = $dbcfg->{user};
$ENV{PGPASSWORD} = $dbcfg->{password};
$ENV{PGDATABASE} = $dbcfg->{name};

exec(
    '/usr/bin/env',
    'psql',
    @ARGV,
);
